name: jasmine
version: 0.0.1
authors:
- Neeraj Mittal <mittal.neeraj@gmail.com>
description: Port of Jasmine to Dart.
homepage: http://neermitt.github.io/jasmine
environment:
  sdk: '>=1.3.6 <2.0.0'
dependencies:
dev_dependencies:
  browser: any
  unittest: '>=0.10.1+2 <0.11.0'
transformers:
